config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'post_books#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :post_books, only: [:new, :create, :index, :show]

  resources :user_profiles, only: [:edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_book.rb
class PostBook < ApplicationRecord

	belongs_to :users

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :post_books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?
	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
	end
end

app/controllers/post_books_controller.rb
class PostBooksController < ApplicationController

	def new
		@post_book = PostBook.new
		@user_info = User.find(params[:user_id])
		@post_books = Post.find(params[:user_id])
	end

	def create
		@post_book = PostBook.new(post_book_params)
		@post_book.save
		redirect_to post_books_path
	end

	def index
		@post_book = PostBook.new
		@user_info = User.find(params[:user_id])
		@post_books = Post.all
	end

	def show
		@post_book = PostBook.new
		@user_info = User.find(params[:user_id])
		@post_books = Post.find(params[:post_book_id])
	end

	def edit
		@post_book = PostBook.find(params[:post_book_id])
	end

	def update
		@post_book = PostBook.find(params[:post_book_id])
		@post_book.update
		redirect_to post_book_path
	end

	def destory
	end

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController

	def edit
		@user_info = User.find(params[:user_id])
	end

	def update
		@user_info = User.find(params[:user_id])
		@user_info.update
		redirect_to post_book_path
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_books_helper.rb
module PostBooksHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post_books/edit.html.erb
<div class="body">
	<div class="container">
		<!-- success message -->
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<h1>Editing Book</h1>
						<!-- 編集フォーム -->
				</div>
			</div>
	</div>
</div>

app/views/post_books/index.html.erb
<div class="col-xs-9">
	<h2>Books</h2>
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th></th>
				<th>Title</th>
				<th>Opnion</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		<tbody>
			<!-- 投稿一覧表示 -->
		</tbody>
	</table>
</div>

app/views/post_books/new.html.erb
<section class="">
	<h2>New book</h2>
	<div class="title">
		<span>Title</span>
		

</section>

app/views/post_books/show.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<nav class="nav navbar-nav navbar-left">
			<span>Bookers></span>
		</nav>
		<nav>
			<% if user_signed_in? %>
				<ul class="nav vavbar navbar-right">
					<li>
						<%= link_to "Home", show_user_path(current_user.id) %>
					</li>
					<li>
						<%= link_to "Users", index_user_path %>
					</li>
					<li>
						<%= link_to "Books", index_post_book_path %>
					</li>
					<li>
						<%= link_to "logout", destroy_user_session_path, method: delete %>
					</li>
				</ul>
			<% else %>
				<ul class="nav navbar-nav navbar-right">
					<li>
						<%= link_to "Home",  %>
					</li>
					<li>
						<%= link_to "About",  %>
					</li>
					<li>
						<%= link_to "sign up", new_user_registration_path %>
					</li>
					<li>
						<%= link_to "login", new_user_sessions_path %>
					</li>
				</ul>
			<% end %>
		</nav>
	</div>
</header>




<div class="col-xs-3">
	<h2>User info</h2>
	<!-- attachment -->
	<table class="table">
		<tbody>
			<tr></tr>
			<tr>
				<th>name</th>
				<th>user name</th>
			</tr>
			<tr>
				<th>introduction</th>
				<th>body</th>
			</tr>
		</tbody>
		<div class="row">
			<!-- profile edit -->
		</div>
		<h2>New book</h2>
		<!-- form for -->
		<%= form_for(@book,url:) do |f| %>
			<label for="book-title">Title</label>
			<%= f.text_field :title %>
			<label for="book-opinion">Opinion</label>
			<%= f.text_field :opinion %>
			<%= f.submit 'Create Book' %>

	</table>
</div>

<div class="col-xs-9">
	<h2>Book detail></h2>
	<table class="table">
		<tbody>
			<tr>
				<td>user</td>
				<td>title</td>
				<td>body</td>
				<td>edit</td>
				<td>destroy</td>
				<!-- user 以外なら -->
				<td>user</td>
				<td>title</td>
				<td>body</td>
			</tr>
		</tbody>
	</table>
</div>














<!-- 以下　間違って作成した文 -->
<div class="col-xs-9">
	<h2>Books</h2>
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th></th>
				<th>Title</th>
				<th>Opnion</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		<tbody>
			<!-- 投稿一覧表示 -->
		</tbody>
	</table>
</div>









<!-- 以下最初に間違って作成 -->
<div class="col-xs-9">
	<h2>Book detail</h2>
	<table class="table">
		<tbody>
			<tr>
				<td>アイコンと名前</td>
				<td>タイトル</td>
				<td>内容</td>
				<td>編集ボタン</td>
				<td>削除ボタン</td>
			</tr>
		</tbody>
	</table>
</div>

app/views/user_profiles/edit.html.erb
<div class="body">
	<div class="container">
		<h2>User info</h2>
		<!-- 編集form -->
	</div>
</div>

app/views/user_profiles/index.html.erb
<div class="col-xs-9">
	<h2>Books</h2>
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th></th>
				<th>Title</th>
				<th>Opnion</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		<tbody>
			<!-- 投稿一覧表示 -->
		</tbody>
	</table>
</div>

app/views/user_profiles/show.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<nav class="nav navbar-nav navbar-left">
			<span>Bookers></span>
		</nav>
		<nav>
			<% if user_signed_in? %>
				<ul class="nav vavbar navbar-right">
					<li>
						<%= link_to "Home", show_user_path(current_user.id) %>
					</li>
					<li>
						<%= link_to "Users", index_user_path %>
					</li>
					<li>
						<%= link_to "Books", index_post_book_path %>
					</li>
					<li>
						<%= link_to "logout", destroy_user_session_path, method: delete %>
					</li>
				</ul>
			<% else %>
				<ul class="nav navbar-nav navbar-right">
					<li>
						<%= link_to "Home",  %>
					</li>
					<li>
						<%= link_to "About",  %>
					</li>
					<li>
						<%= link_to "sign up", new_user_registration_path %>
					</li>
					<li>
						<%= link_to "login", new_user_sessions_path %>
					</li>
				</ul>
			<% end %>
		</nav>
	</div>
</header>




<div class="col-xs-3">
	<h2>User info</h2>
	<!-- attachment -->
	<table class="table">
		<tbody>
			<tr></tr>
			<tr>
				<th>name</th>
				<th>user name</th>
			</tr>
			<tr>
				<th>introduction</th>
				<th>body</th>
			</tr>
		</tbody>
		<div class="row">
			<!-- profile edit -->
		</div>
		<h2>New book</h2>
		<!-- form for -->
		<%= form_for(@book,url:) do |f| %>
			<label for="book-title">Title</label>
			<%= f.text_field :title %>
			<label for="book-opinion">Opinion</label>
			<%= f.text_field :opinion %>
			<%= f.submit 'Create Book' %>

	</table>
</div>

<div class="col-xs-9">
	<h2>Books</h2>
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th></th>
				<th>Title</th>
				<th>Opnion</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		<tbody>
			<!-- 投稿一覧表示 -->
		</tbody>
	</table>
</div>









<!-- 以下最初に間違って作成 -->
<div class="col-xs-9">
	<h2>Book detail</h2>
	<table class="table">
		<tbody>
			<tr>
				<td>アイコンと名前</td>
				<td>タイトル</td>
				<td>内容</td>
				<td>編集ボタン</td>
				<td>削除ボタン</td>
			</tr>
		</tbody>
	</table>
</div>